name: Build and Publish Docker Images (Legacy)

on:
  schedule:
    - cron: '0 5 * * *'
    - cron: '0 17 * * *'
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  setup-timestamp:
    # Run the job if triggered by a scheduled event or a push with a specific commit message
    if: github.event_name == 'schedule' || (github.event_name == 'push' && contains(github.event.head_commit.message, 'run-ci'))
    runs-on: ubuntu-24.04
    outputs:
      date: ${{ steps.timestamp.outputs.date }}
      date_time: ${{ steps.timestamp.outputs.date_time }}
    steps:
      - name: Generate build timestamp
        id: timestamp
        run: |
          date=$(date '+%Y-%m-%d')
          date_time=$(date '+%Y-%m-%d.%H-%M-%S')
          echo "date=$date" >> $GITHUB_OUTPUT
          echo "date_time=$date_time" >> $GITHUB_OUTPUT

  build-amd64:
    needs: setup-timestamp
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up BuildKit Docker container builder
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry except on PR
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          registry_lower=$(echo "${{ env.REGISTRY }}" | tr '[:upper:]' '[:lower:]')
          image_name_lower=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          commit_hash="${{ github.sha }}"
          
          # Use timestamp from setup job
          date="${{ needs.setup-timestamp.outputs.date }}"
          date_time="${{ needs.setup-timestamp.outputs.date_time }}"

          base_image="${registry_lower}/${image_name_lower}"

          find . -name 'Dockerfile' | sort -r | while IFS= read -r dockerfile; do
            dir=$(dirname "$dockerfile")
            image_name_dir=$(basename "$dir" | tr '[:upper:]' '[:lower:]')
            image_name_dir="${image_name_dir}.legacy-build"

            tags=(
              "${base_image}:${image_name_dir}.amd64"
              "${base_image}:${image_name_dir}.latest.amd64"
              "${base_image}:${image_name_dir}.${date}.amd64"
              "${base_image}:${image_name_dir}.${date_time}.amd64"
              "${base_image}:${image_name_dir}.${commit_hash}.amd64"
              "${base_image}:${image_name_dir}.${commit_hash}.${date}.amd64"
              "${base_image}:${image_name_dir}.${commit_hash}.${date_time}.amd64"
            )

            echo "Building image for ${tags[0]} with tags:"
            for tag in "${tags[@]}"; do
              echo " - $tag"
            done

            buildx_cmd="docker buildx build --platform linux/amd64 --push"
            for tag in "${tags[@]}"; do
              buildx_cmd+=" --tag $tag"
            done
            buildx_cmd+=" \"$dir\" --file \"$dockerfile\""

            eval $buildx_cmd

            for tag in "${tags[@]}"; do
              docker rmi "$tag" || true
            done
          done

  build-arm64:
    needs: setup-timestamp
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up BuildKit Docker container builder
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry except on PR
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        run: |
          registry_lower=$(echo "${{ env.REGISTRY }}" | tr '[:upper:]' '[:lower:]')
          image_name_lower=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          commit_hash="${{ github.sha }}"
          
          # Use timestamp from setup job
          date="${{ needs.setup-timestamp.outputs.date }}"
          date_time="${{ needs.setup-timestamp.outputs.date_time }}"

          base_image="${registry_lower}/${image_name_lower}"

          find . -name 'Dockerfile' | sort -r | while IFS= read -r dockerfile; do
            dir=$(dirname "$dockerfile")
            image_name_dir=$(basename "$dir" | tr '[:upper:]' '[:lower:]')
            image_name_dir="${image_name_dir}.legacy-build"

            tags=(
              "${base_image}:${image_name_dir}.arm64"
              "${base_image}:${image_name_dir}.latest.arm64"
              "${base_image}:${image_name_dir}.${date}.arm64"
              "${base_image}:${image_name_dir}.${date_time}.arm64"
              "${base_image}:${image_name_dir}.${commit_hash}.arm64"
              "${base_image}:${image_name_dir}.${commit_hash}.${date}.arm64"
              "${base_image}:${image_name_dir}.${commit_hash}.${date_time}.arm64"
            )

            echo "Building image for ${tags[0]} with tags:"
            for tag in "${tags[@]}"; do
              echo " - $tag"
            done

            buildx_cmd="docker buildx build --platform linux/arm64 --push"
            for tag in "${tags[@]}"; do
              buildx_cmd+=" --tag $tag"
            done
            buildx_cmd+=" \"$dir\" --file \"$dockerfile\""

            eval $buildx_cmd

            for tag in "${tags[@]}"; do
              docker rmi "$tag" || true
            done
          done

  create-manifest:
    needs: [setup-timestamp, build-amd64, build-arm64]
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      id-token: write
    steps:
      # Login against a Docker registry except on PR
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifests
        run: |
          registry_lower=$(echo "${{ env.REGISTRY }}" | tr '[:upper:]' '[:lower:]')
          image_name_lower=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          commit_hash="${{ github.sha }}"
          
          # Use timestamp from setup job
          date="${{ needs.setup-timestamp.outputs.date }}"
          date_time="${{ needs.setup-timestamp.outputs.date_time }}"

          find . -name 'Dockerfile' | sort -r | while read -r dockerfile; do
            dir=$(dirname "$dockerfile")
            image_name_dir=$(basename "$dir" | tr '[:upper:]' '[:lower:]')
            image_name_dir="${image_name_dir}.legacy-build"

            base_tags=(
              "${image_name_dir}"
              "${image_name_dir}.latest"
              "${image_name_dir}.${date}"
              "${image_name_dir}.${date_time}"
              "${image_name_dir}.${commit_hash}"
              "${image_name_dir}.${commit_hash}.${date}"
              "${image_name_dir}.${commit_hash}.${date_time}"
            )

            for base_tag in "${base_tags[@]}"; do
              amd64_tag="${registry_lower}/${image_name_lower}:${base_tag}.amd64"
              arm64_tag="${registry_lower}/${image_name_lower}:${base_tag}.arm64"
              manifest_tag="${registry_lower}/${image_name_lower}:${base_tag}"

              docker manifest create $manifest_tag --amend $amd64_tag --amend $arm64_tag
              docker manifest push $manifest_tag
            done
          done