name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker run --privileged --rm tonistiigi/binfmt --install all
        docker buildx build --platform linux/arm64 . --file rdesktop-debian-xfce-arm64/Dockerfile --tag rdesktop-debian-xfce-arm64:$(date +%s)
